### ISSUE TITLE
Missing jpeg

### ISSUE THREAD

**Issue by snowman2** [conda-forge/pygrib-feedstock#14]
I installed pygrib:

$ conda install -c conda-forge pygrib

I tested import:

>>> import pygrib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory

I installed jpeg:

$ conda install -c conda-forge jpeg

Now all is well. Please add jpeg to dependencies :)

**Comment by ocefpaf** [comment]
`pygrib` depends on [`jasper`](https://github.com/conda-forge/pygrib-feedstock/blob/master/recipe/meta.yaml#L23), an `jasper` depends on [`jpeg`](https://github.com/conda-forge/jasper-feedstock/blob/master/recipe/meta.yaml#L16). Those are properly specified and pinned as you can see from if you click on the links there.

What happened in your environment was probably a big mix of packages between `conda-forge` (that uses `jpeg 9*`) and `defaults` (that uses `jpeg 8*`). Unfortunately `conda` is known to break the pinning, like we have in `jasper` and install `jpeg 8*`.

Manually installing it, like what you did, may break other packages pulled from `defaults` that were compiled against `jpeg 8*`. The proper solution is to install everything in a environment with the `conda-forge` on top of `defaults` to use conda's channel preference feature.

**Comment by snowman2** [comment]
OK. Thanks!

**Comment by ocefpaf** [comment]
BTW, if you type `conda list` before trying to force install `jpeg` again you will see the bad `jpeg 8*` there.
