### ISSUE TITLE
pygrib 2.0.2 on OSX, PY 3.5: missing libjpeg.9.dylib

### ISSUE THREAD

**Issue by efiring** [conda-forge/pygrib-feedstock#15]
Import of pygrib fails (first block below); I also note that libjpeg does not appear in the dependency list (second block below).

```
(test) efiring@manini2:~/work/teaching/data_analysis/2017/Alex$ conda list pygrib
# packages in environment at /Users/efiring/anaconda/envs/test:
#
pygrib                    2.0.2                    py35_0    conda-forge
(test) efiring@manini2:~/work/teaching/data_analysis/2017/Alex$ ipython
Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pygrib
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6160c29be9fd> in <module>()
----> 1 import pygrib

ImportError: dlopen(/Users/efiring/anaconda/envs/test/lib/python3.5/site-packages/pygrib.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: /Users/efiring/anaconda/envs/test/lib/libgrib_api.dylib
  Reason: image not found
```
From "conda info pygrib":
```
pygrib 2.0.2 py35_0
-------------------
file name   : conda-forge::pygrib-2.0.2-py35_0.tar.bz2
name        : pygrib
version     : 2.0.2
build number: 0
build string: py35_0
channel     : conda-forge
size        : 794 KB
arch        : x86_64
binstar     : {'package_id': '571135515351d85fceeb3a57', 'owner_id': '5528f42ce1dad12974506e8d', 'channel': 'main'}
fn          : pygrib-2.0.2-py35_0.tar.bz2
has_prefix  : True
license     : MIT
license_family: MIT
machine     : x86_64
md5         : 3b65d79bd59441ade840f0f82e161ddb
operatingsystem: darwin
platform    : osx
priority    : 0
schannel    : conda-forge
subdir      : osx-64
target-triplet: x86_64-any-darwin
url         : https://conda.anaconda.org/conda-forge/osx-64/pygrib-2.0.2-py35_0.tar.bz2
dependencies:
    ecmwf_grib
    jasper
    libpng >=1.6.23,<1.7
    numpy
    pyproj
    python 3.5*
```

**Comment by ocefpaf** [comment]
Eric I believe you are hitting the  channel mismatch problem (see
http://conda-forge.github.io/docs/conda-forge_gotchas.html for more info).

In conda-forge we use jpeg 9* while defaults use jpeg 8* (try conda list
and you'll probably see version 8 there instead of 9). Changing the channel
priority is the 'right' way to fix this, but sometimes force installing
jpeg 9 fix this too.

Note that we don't specify jpeg as a direct dependency because jasper
depends on it.

**Comment by efiring** [comment]
`conda update jpeg; conda update jasper` fixed it; but all of this seems to reflect a breakdown of the dependency checking system.  Whether the problem is in conda itself, or in the feedstocks, I don't know.  I have run into this before in mixing conda-forge with default; I think the last time it was a libnetcdf4 problem.

**Comment by ocefpaf** [comment]
> but all of this seems to reflect a breakdown of the dependency checking system.  Whether the problem is in conda itself, or in the feedstocks, I don't know.  I have run into this before in mixing conda-forge with default; I think the last time it was a libnetcdf4 problem.

Did you check http://conda-forge.github.io/docs/conda-forge_gotchas.html ? It should be explained there. Let me know if the text is unclear. This problem is still poorly understood by most users and we are in the process of writing docs to explain it.

**Comment by efiring** [comment]
Yes, I read that--but it is just confirming that full dependency checking is not being done, and/or full and correct dependency specifications are not being provided by the recipes.  In my case here, I installed a package that had an *actual* requirement for a newer version of a library than what was present.  That installation did *not* trigger a dependency check that could and should have detected the need for that version.  What is the technical reason for this failure of dependency checking?  Is it entirely a limitation of conda?  Or is it an omission in some of the package dependency specifications?

**Comment by rahulbhat44** [comment]
sudo python -m pip install pygrib

**Comment by ocefpaf** [comment]
> sudo python -m pip install pygrib

Please never recommend `sudo pip`.
