### ISSUE TITLE
Installing pygrib with conda-forge

### ISSUE THREAD

**Issue by muuud** [conda-forge/pygrib-feedstock#18]
Hello, I am trying to install pygrib using this repository, and have followed the instructions given.

When I try to import the pygrib module in a script, I receive the following error:

```
ImportError: dlopen(/Users/Alex/miniconda2/lib/python2.7/site-packages/pygrib.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: /Users/Alex/miniconda2/lib/libgrib_api.dylib
  Reason: image not found
```

Is there something I am missing? My installation of conda could sometimes be a bit weird as I accidentally installed it using sudo and now everything requires sudo.

**Comment by ocefpaf** [comment]
> My installation of conda could sometimes be a bit weird as I accidentally installed it using sudo and now everything requires sudo.

I highly recommend you to reinstall it in your user space. That could be the culprit here.

I don't have a `OS X` system to try this but those files are in the packages and the Linux version is working properly.

**Comment by dopplershift** [comment]
For me on osx, creating a new environment with `conda create -n test-grib python=2.7 pygrib` allows me to run `python -c 'import pygrib'` without error.

**Comment by muuud** [comment]
This works! However, in doing this, I'm not actually sure what I am doing. Do I always have to restart this test environment when running a script with pygrib? Basically, how can I be sure that it'll work at anytime

**Comment by ocefpaf** [comment]
You have to always activate the environment to be able to use what is installed there.

One alternative, that I do not recommend, is to install the packages in your root environment.
But that can be messy and lead to a broken environment very easily when mixing packages and channels.

Closing this b/c the package is working. Feel free ask more question here though.
