### ISSUE TITLE
Cannot import pygrib

### ISSUE THREAD

**Issue by malloryrow** [conda-forge/pygrib-feedstock#8]
I have tried using 'conda install' to install pygrib. When I got to import pygrib, I get 'ImportError: libgrib_api.so.1: cannot open shared object file: No such file or directory'. I can see the 'libgrid_api.so' in my /lib, but no libgrib_api.so.1.  I am on a Linux machine using python2.7.

**Comment by ocefpaf** [comment]
I can confirm that. Weird it did not surfaced build time :confused: 

Working on it...

**Comment by ocefpaf** [comment]
@malloryrow the latest two updates in `ecmwf_grib` do not produce the `.so.1` file. Re-building should fix this. Meanwhile you can downgrade `ecmwf_grib` to `1.14.7`.

**Comment by malloryrow** [comment]
Thank you! Appreciate it!
